version: "3.4"

services:
  
  app-a:
    # build: ../app/fastapi-otel/
    image: ghcr.io/blueswen/observability-ironman30-lab/fastapi-otel:latest
    container_name: app-a
    ports:
      - "8000:8000"
    environment:
      APP_NAME: "app-a"
      TARGET_ONE_SVC: "app-b:8000"
      TARGET_TWO_SVC: "app-c:8000"
      OTLP_GRPC_ENDPOINT: "http://alloy:4317"
    command: "python main.py"

  app-b:
    # build: ../app/fastapi-otel/
    image: ghcr.io/blueswen/observability-ironman30-lab/fastapi-otel:latest
    container_name: app-b
    ports:
      - "8001:8000"
    environment:
      APP_NAME: "app-b"
      TARGET_ONE_SVC: "app-c:8000"
      TARGET_TWO_SVC: "app-a:8000"
      OTLP_GRPC_ENDPOINT: "http://alloy:4317"
    command: "python main.py"

  app-c:
    # build: ../app/fastapi-otel/
    image: ghcr.io/blueswen/observability-ironman30-lab/fastapi-otel:latest
    container_name: app-c
    ports:
      - "8002:8000"
    environment:
      APP_NAME: "app-c"
      TARGET_ONE_SVC: "app-a:8000"
      TARGET_TWO_SVC: "app-b:8000"
      OTLP_GRPC_ENDPOINT: "http://alloy:4317"
    command: "python main.py"

  alloy:
    image: grafana/alloy:v1.2.0
    container_name: alloy
    ports:
      - "12345:12345"
      - "12348:12348"
      - "6832:6832"
      - "55679:55679"
    volumes:
      - ./etc/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy

  mimir:
    image: grafana/mimir:2.12.0
    container_name: mimir
    ports:
      - 9009:9009
    volumes:
      - ./etc/mimir.yaml:/etc/mimir/mimir.yaml
    command:
      - -usage-stats.enabled=false
      - -config.file=/etc/mimir/mimir.yaml
    depends_on:
      - minio

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./etc/loki.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml
    depends_on:
      - minio

  tempo:
    image: grafana/tempo:2.5.0
    container_name: tempo
    volumes:
      - ./etc/tempo.yaml:/etc/tempo/tempo.yaml
    command: 
      - "--target=all"
      - "--auth.enabled=false"
      - "--config.file=/etc/tempo/tempo.yaml"
    depends_on:
      - minio

  minio:
    image: minio/minio:RELEASE.2024-06-28T09-06-49Z
    container_name: minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        mkdir -p /data/mimir-data && \
        mkdir -p /data/mimir-ruler && \
        mkdir -p /data/tempo && \
        minio server /data --console-address :9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./.data/minio:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 15s
      timeout: 20s
      retries: 5

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_FEATURE_TOGGLES_ENABLE: "tempoServiceGraph,traceToMetrics"
    volumes:
      - ./etc/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
