version: "3.7"

services:

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
      - ./etc/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./etc/grafana/dashboards:/etc/grafana/dashboards

  graphite-statsd:
    image: graphiteapp/graphite-statsd:1.1.10-5
    container_name: graphite-statsd
    ports:
      - 80:80
      - 8080:8080
      - 8125:8125/udp
      - 8126:8126

  flask-pystatsd:
    # build: ../app/flask-pystatsd/
    image: ghcr.io/blueswen/observability-ironman30-lab/flask-pystatsd:latest
    container_name: flask
    environment:
      - STATSD_HOST=graphite-statsd
      - STATSD_PORT=8125
    ports:
      - "8000:8000"
    depends_on:
      - graphite-statsd
