version: "3.7"

services:

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
      - ./etc/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./etc/grafana/dashboards:/etc/grafana/dashboards

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./etc/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml

  statsd-exporter:
    image: prom/statsd-exporter:v0.26.1
    container_name: statsd-exporter
    ports:
      - "9125:9125"
      - "9102:9102"

  flask-datadog:
    # build: ../app/flask-datadog/
    image: ghcr.io/blueswen/observability-ironman30-lab/flask-datadog:latest
    container_name: flask
    environment:
      - STATSD_HOST=statsd-exporter
      - STATSD_PORT=9125
    ports:
      - "8000:8000"
    depends_on:
      - statsd-exporter
