version: "3.7"

services:

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./etc/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml

  fastapi:
    # build: ../app/fastapi/
    image: ghcr.io/blueswen/observability-ironman30-lab/fastapi:latest
    container_name: fastapi
    ports:
      - "8000:8000"
    command: "python main.py"

  spring-boot:
    # build: ../app/springboot/
    image: ghcr.io/blueswen/observability-ironman30-lab/springboot:latest
    container_name: spring-boot
    ports:
      - "8080:8080"
    command: "java -jar /app.jar"

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
      - ./etc/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./etc/grafana/dashboards:/etc/grafana/dashboards
