management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: spring-boot-demo-app
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
