# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - uid: tempo-1
    orgId: 1
    name: Tempo-1
    type: tempo
    typeName: Tempo
    access: proxy
    url: http://tempo-1
    isDefault: true
    readOnly: false
    editable: true
  - uid: tempo-2
    orgId: 1
    name: Tempo-2
    type: tempo
    typeName: Tempo
    access: proxy
    url: http://tempo-2
    isDefault: false
    readOnly: false
    editable: true
