version: "3.7"

services:

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
      - ./etc/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./etc/grafana/dashboards:/etc/grafana/dashboards

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./etc/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml

  mimir:
    image: grafana/mimir:2.12.0
    container_name: mimir
    ports:
      - 9009:9009
    volumes:
      - ./etc/mimir/mimir.yaml:/etc/mimir/mimir.yaml
    command:
      - -usage-stats.enabled=false
      - -config.file=/etc/mimir/mimir.yaml

