version: "3.4"

services:
  
  app-a:
    build: ./app_fastapi/
    container_name: app-a
    ports:
      - "8000:8000"
    volumes:
      - ./app_fastapi/:/app
    environment:
      APP_NAME: "app-a"
      TARGET_ONE_SVC: "app-b:8000"
      TARGET_TWO_SVC: "app-c:8000"
      OTLP_GRPC_ENDPOINT: "http://grafana-agent:4317"
    command: "python main.py"

  app-b:
    build: ./app_fastapi/
    container_name: app-b
    ports:
      - "8001:8000"
    environment:
      APP_NAME: "app-b"
      TARGET_ONE_SVC: "app-c:8000"
      TARGET_TWO_SVC: "app-a:8000"
      OTLP_GRPC_ENDPOINT: "http://grafana-agent:4317"
    command: "python main.py"

  app-c:
    build: ./app_fastapi/
    container_name: app-c
    ports:
      - "8002:8000"
    environment:
      APP_NAME: "app-c"
      TARGET_ONE_SVC: "app-a:8000"
      TARGET_TWO_SVC: "app-b:8000"
      OTLP_GRPC_ENDPOINT: "http://grafana-agent:4317"
    command: "python main.py"

  grafana-agent:
    image: grafana/agent:v0.37.1
    container_name: grafana-agent
    ports:
      - "12345:12345"
      - "12348:12348"
      - "6832:6832"
      - "55679:55679"
    volumes:
      - ./etc/agent/config.river:/etc/agent/agent.river
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AGENT_MODE: flow
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "/etc/agent/agent.river",
    ]

  tempo:
    image: grafana/tempo:2.2.3
    container_name: tempo
    command: 
      - "--target=all"
      - "--storage.trace.backend=local"
      - "--storage.trace.local.path=/var/tempo"
      - "--auth.enabled=false"

  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus
    command:
      - "--enable-feature=remote-write-receiver"
      - "--enable-feature=exemplar-storage"
      - "--config.file=/workspace/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus:/workspace

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_FEATURE_TOGGLES_ENABLE: "tempoServiceGraph,traceToMetrics"
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
