# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - uid: pyroscope
    orgId: 1
    name: Pyroscope
    type: grafana-pyroscope-datasource
    typeName: Grafana Pyroscope
    url: "http://pyroscope:4040"
    isDefault: true
    readOnly: false
  - uid: tempo
    orgId: 1
    name: Tempo
    type: tempo
    typeName: Tempo
    access: proxy
    url: http://tempo
    isDefault: false
    jsonData:
      httpMethod: GET
  - uid: prometheus
    orgId: 1
    name: Prometheus
    type: prometheus
    typeName: Prometheus
    access: proxy
    url: http://prometheus:9090
    password: ''
    user: ''
    database: ''
    basicAuth: false
    jsonData:
      httpMethod: POST
    readOnly: false
