# Source: https://github.com/jaegertracing/jaeger/blob/main/docker-compose/kafka/docker-compose.yml

version: "3.4"

services:
  
  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
    container_name: k6-tracing
    environment:
      - ENDPOINT=jaeger-collector:4317
    restart: always
    depends_on:
      - jaeger-collector

  zookeeper:
    image: bitnami/zookeeper:3.9.1
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    image: 'bitnami/kafka:3.5.1'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    restart: always
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --list --bootstrap-server 127.0.0.1:9092"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  jaeger-remote-storage:
    image: jaegertracing/jaeger-remote-storage:1.50.0
    container_name: jaeger-remote-storage
    ports:
      - 17271:17271
    environment:
      - SPAN_STORAGE_TYPE=memory
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:17270/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.50.0
    container_name: jaeger-collector
    command:
      - "--collector.otlp.enabled=true"
      - "--log-level=debug"
    ports:
      - 4318:4318
      - 14250:14250
    environment:
      - SPAN_STORAGE_TYPE=kafka
      - KAFKA_PRODUCER_BROKERS=kafka:9092
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:14269/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      kafka:
        condition: service_healthy

  jaeger-ingester:
    image: jaegertracing/jaeger-ingester:1.50.0
    container_name: jaeger-ingester
    command:
      - "--grpc-storage.server=jaeger-remote-storage:17271"
      - "--log-level=debug"
    environment:
      - SPAN_STORAGE_TYPE=grpc-plugin
      - KAFKA_CONSUMER_BROKERS=kafka:9092
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:14270/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      kafka:
        condition: service_healthy
      jaeger-remote-storage:
        condition: service_healthy
      jaeger-collector:
        condition: service_healthy

  jaeger-query:
    image: jaegertracing/jaeger-query:1.50.0
    container_name: jaeger-query
    command:
      - "--grpc-storage.server=jaeger-remote-storage:17271"
      - "--log-level=debug"
    environment:
      - SPAN_STORAGE_TYPE=grpc-plugin
    ports:
      - "16686:16686"
      - "16687"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:16687/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      jaeger-remote-storage:
        condition: service_healthy
