version: "3.7"

services:

  fastapi:
    # build: ../app/fastapi/
    image: ghcr.io/blueswen/observability-ironman30-lab/fastapi:latest
    container_name: fastapi
    ports:
      - "8000:8000"
    labels:
      - logging=promtail

  nginx:
    image: nginxdemos/hello:0.4
    container_name: nginx
    ports:
      - "8080:80"
    labels:
      - logging=promtail

  loki-read:
    image: grafana/loki:3.0.0
    container_name: loki-read
    volumes:
      - ./etc/loki/config.yaml:/etc/loki/config.yaml
    command: "-config.file=/etc/loki/config.yaml -target=read -query-scheduler.use-scheduler-ring=false"
    ports:
      - 3101:3100
      - 7946
      - 9095
    labels:
      - logging=promtail
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - minio
  
  loki-write:
    image: grafana/loki:3.0.0
    container_name: loki-write
    volumes:
      - ./etc/loki/config.yaml:/etc/loki/config.yaml
    command: "-config.file=/etc/loki/config.yaml -target=write"
    ports:
      - 3102:3100
      - 7946
      - 9095
    labels:
      - logging=promtail
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - minio

  loki-gateway:
    image: nginx:latest
    container_name: loki-gateway
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - loki-read
      - loki-write
    ports:
      - "3100:3100"
    labels:
      - logging=promtail

  minio:
    image: minio/minio:RELEASE.2024-06-28T09-06-49Z
    container_name: minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data --console-address :9001
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./.data/minio:/data
    labels:
      - logging=promtail
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 15s
      timeout: 20s
      retries: 5

  promtail:
    image:  grafana/promtail:3.0.0
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - ./etc/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - logging=promtail
    command: -config.file=/etc/promtail/docker-config.yaml

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    command:
      - "--enable-feature=exemplar-storage"
      - "--config.file=/workspace/prometheus.yml"
    labels:
      - logging=promtail
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus:/workspace

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - 3000:3000
    labels:
      - logging=promtail
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
      - ./etc/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./etc/grafana/dashboards:/etc/grafana/dashboards
