version: "3.4"

services:
  
  fastapi:
    # build: ../app/fastapi/
    image: ghcr.io/blueswen/observability-ironman30-lab/fastapi:latest
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      TARGET_ONE_SVC: "fastapi:8000"
      TARGET_TWO_SVC: "spring-boot:8080"
      APP_NAME: fastapi
      PYROSCOPE_SERVER: http://pyroscope:4040
      ENABLE_PYROSCOPE: "true"
    volumes:
      - ../app/fastapi/:/app
    command: "python main.py"
    depends_on:
      - pyroscope

  spring-boot:
    # build: ../app/springboot/
    image: ghcr.io/blueswen/observability-ironman30-lab/springboot:latest
    container_name: spring-boot
    ports:
      - "8080:8080"
    environment:
      TARGET_ONE_SVC: "spring-boot:8080"
      TARGET_TWO_SVC: "fastapi:8000"
      PYROSCOPE_APPLICATION_NAME: spring-boot
      PYROSCOPE_SERVER_ADDRESS: http://pyroscope:4040
    command: "java -javaagent:/pyroscope.jar -jar /app.jar"

  pyroscope:
    image: grafana/pyroscope:1.6.1
    container_name: pyroscope
    ports:
      - "4040:4040"

  alloy:
    image: grafana/alloy:v1.2.0
    container_name: alloy
    user: root
    privileged: true
    pid: 'host'
    ports:
      - '12345:12345'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc/config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
