name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push FastAPI image
        uses: docker/build-push-action@v6
        with:
          context: ./app/fastapi
          push: true
          tags: ghcr.io/${{ github.repository }}/fastapi:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push FastAPI OTEL image
        uses: docker/build-push-action@v6
        with:
          context: ./app/fastapi-otel
          push: true
          tags: ghcr.io/${{ github.repository }}/fastapi-otel:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push Flask Datadog image
        uses: docker/build-push-action@v6
        with:
          context: ./app/flask-datadog
          push: true
          tags: ghcr.io/${{ github.repository }}/flask-datadog:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push Flask pystatsd image
        uses: docker/build-push-action@v6
        with:
          context: ./app/flask-pystatsd
          push: true
          tags: ghcr.io/${{ github.repository }}/flask-pystatsd:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push Spring Boot image
        uses: docker/build-push-action@v6
        with:
          context: ./app/springboot
          push: true
          tags: ghcr.io/${{ github.repository }}/springboot:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push todo app backend image
        uses: docker/build-push-action@v6
        with:
          context: ./app/todo-app/backend
          push: true
          tags: ghcr.io/${{ github.repository }}/todo-app/backend:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push todo app frontend jquery image
        uses: docker/build-push-action@v6
        with:
          context: ./app/todo-app/jquery-app
          push: true
          tags: ghcr.io/${{ github.repository }}/todo-app/jquery-app:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push todo app frontend vue image
        uses: docker/build-push-action@v6
        with:
          context: ./app/todo-app/vue-app
          push: true
          tags: ghcr.io/${{ github.repository }}/todo-app/vue-app:latest
          platforms: linux/amd64,linux/arm64

